--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/home/nf/ws/td/potato/al_ip/bram.vhd
 -- Date	:	2019 07 30
 -- TD version	:	4.5.12562
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY instruction_rom IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(10 DOWNTO 0);
	clka		: IN STD_LOGIC;
	rsta		: IN STD_LOGIC
	);
END instruction_rom;

ARCHITECTURE struct OF instruction_rom IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 32,
			ADDR_WIDTH_A	=> 11,
			DATA_DEPTH_A	=> 2048,
			DATA_WIDTH_B	=> 32,
			ADDR_WIDTH_B	=> 11,
			DATA_DEPTH_B	=> 2048,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			RESETMODE	=> "SYNC",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "NONE",
			FILL_ALL		=> "00000000000000000000000000000000"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> rsta,
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
